name: Android CI Build APK

on:
  push:
    branches:
      - main # Triggers on pushes to the main branch
  pull_request:
    branches:
      - main # Also triggers on pull requests to the main branch (optional)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3 # Using a dedicated Android setup action
      # No specific SDK versions needed here as compileSdkVersion from build.gradle will be used

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug # Builds the debug APK
      # For release builds, you would use ./gradlew assembleRelease
      # and need to manage signing keys (e.g., using GitHub Secrets)

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug # Name of the artifact
        path: app/build/outputs/apk/debug/app-debug.apk # Path to the generated APK 